POST http://localhost:8000/registerDriver
Content-Type: application/json

{
    "username" : "hlalele",
     "phonenumber": 5621440,
     "email": "hlalele6.gmail.com",
     "licensenumber" : "12mtysgd",
      "location": "Masowe",
      "password": "123456",
      "confirm" : "123456"
}